# This file was generated by GoReleaser. DO NOT EDIT.
class LocalWeather < Formula
  desc "Lightweight CLI for quickly checking the current weather."
  homepage ""
  version "0.1.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v0.1.5/local-weather_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "357520c77cd28975962ea9b3e6fe1c5c1484e6b2de00b89c367adb6fd9f3f5eb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v0.1.5/local-weather_0.1.5_Linux_x86_64.tar.gz"
      sha256 "3678e50acd4706677f2f975c1568c5bbcb401af50cad20656c4b8f7cc499463f"
    end
  end

  def install
    bin.install "local-weather"
  end
end
