# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalWeatherCliGo < Formula
  desc "Lightweight CLI for quickly checking the current weather."
  homepage "https://github.com/justinrsmith/local-weather-cli-go"
  version "2.0.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.2/local-weather-cli-go_Darwin_x86_64.tar.gz"
      sha256 "27f697419400c5e8f30ccb1e15981bf90f9a332b216da4ce7a128e35cb881c66"

      def install
        bin.install "local-weather-cli-go"
      end
    end
    on_arm do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.2/local-weather-cli-go_Darwin_arm64.tar.gz"
      sha256 "b23c4cd77ff1b69dfb3e410be54d529b4b6933e9829bda4657e6a46b1a6a201e"

      def install
        bin.install "local-weather-cli-go"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.2/local-weather-cli-go_Linux_x86_64.tar.gz"
        sha256 "8a6cf3ef1966115ae2b315f050b9717c5d3cd018fc4cb3cf15d30caa85e4bcc2"

        def install
          bin.install "local-weather-cli-go"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.2/local-weather-cli-go_Linux_arm64.tar.gz"
        sha256 "ff7ae6185e0218288abba24168e8d0bf21962be8a15858b7d71d27496f5799bf"

        def install
          bin.install "local-weather-cli-go"
        end
      end
    end
  end
end
