# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalWeather < Formula
  desc "Lightweight CLI for quickly checking the current weather."
  homepage "https://github.com/justinrsmith/local-weather-cli-go"
  version "2.0.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.5/local-weather-cli-go_Darwin_x86_64.tar.gz"
      sha256 "450bc64fd336ae2639e6c388e0495c29b6444a7350a4a7c412c50d29fd1d87e4"

      def install
        bin.install "local-weather"
      end
    end
    on_arm do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.5/local-weather-cli-go_Darwin_arm64.tar.gz"
      sha256 "8526c2b90a03c78980cd9d4852f1ad4ce58db4bb488fda428ba75d44e236be15"

      def install
        bin.install "local-weather"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.5/local-weather-cli-go_Linux_x86_64.tar.gz"
        sha256 "126f9a633499f32986c61f8b101c64d64bae419d9229718e55b0d1597e02ffff"

        def install
          bin.install "local-weather"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.5/local-weather-cli-go_Linux_arm64.tar.gz"
        sha256 "564ca05402d685f80fd8fde9b35d7ddd90ef64f72581074fddc015ef40f2a6a6"

        def install
          bin.install "local-weather"
        end
      end
    end
  end
end
