# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalWeather < Formula
  desc "Lightweight CLI for quickly checking the current weather."
  homepage "https://github.com/justinrsmith/local-weather-cli-go"
  version "2.0.15"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.15/local-weather-cli-go_Darwin_x86_64.tar.gz"
      sha256 "e0781733f38210c8e00dba56d6d398dd92cdffa47e24fb8e9620e39fce9259f5"

      def install
        bin.install "local-weather"
      end
    end
    on_arm do
      url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.15/local-weather-cli-go_Darwin_arm64.tar.gz"
      sha256 "92207ad3d3bc8c6abc7e7a0dba2c39539663d29945731f42227db3de681015f6"

      def install
        bin.install "local-weather"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.15/local-weather-cli-go_Linux_x86_64.tar.gz"
        sha256 "71269e540573bee704b25b99dd87934254f314f4913f220f2ff7433124b6891a"

        def install
          bin.install "local-weather"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/justinrsmith/local-weather-cli-go/releases/download/v2.0.15/local-weather-cli-go_Linux_arm64.tar.gz"
        sha256 "2450bbf98e1cfb9655a96ad9f2c1fe0cbfc7df689d22412629e738e97f0d54ac"

        def install
          bin.install "local-weather"
        end
      end
    end
  end
end
